### ISSUE TITLE
implementation issues on server side

### ISSUE THREAD

**Issue by Tr3ffel** [feathersjs-offline/owndata-ownnet#9]
Hi, I'm currently testing this new library and discovered two problems while implementing it on server side.

### Problem 1:
`setup(app, path)` is not called for the wrapped service which is important if you want to access the `app` object inside a service method (i.e. for internally calling other services). 
I've created a Pull Request for this. I hope it helps.

### Problem 2:
For some reason all my `hooks` are getting ignored if I call my wrapped service via Postman (HTTP). Also `context.path` is `undefined` for the request which should normally contain the service name. 
But if I call the service via `socket.io` everything works fine. This problem also seems to be present in the `simple-example` repository. I could not find out why this happens, so I hope someone else could maybe fix this problem.

And thanks for the effort making this library. It would be great for many people not having to manually programming all the code for offline-first applications.

**Comment by mhillerstrom** [comment]
Problem 1 is solved for both server and client in v1.0.3.

Problem 2 is much trickier: there is a difference between the transports REST and socket.io for listeners, but I cannot for the life of me see why. REST acknowledges and activate listeners on the service being wrapped whereas socket.io does not. However, both transports acknowledge listeners attached to the wrapped service. So, for now I recommend to set listeners on both the wrapped service and its `.remote` counterpart.

In version v1.0.4 I believe hooks attached to the original service are handled correct by the wrappers ie. both transports activates hooks as expected. This follows the "natural" way of development as far as this lets the developer use the feathers-cli scaffolding.

If you can confirm the above in your test case I will change the documentation pending a real solution.

**Comment by Tr3ffel** [comment]
Hi, thanks for the help. 

But I'm still not sure if everthing works correctly. Even if I don't use any hooks the `updatedAt`, `onServerAt`, `uuid` will not be set when using Postman (REST-Transport). Shouldn't this be done by default?
